### ISSUE TITLE
When attempting to install and run "Face App" from video linked in description, an error is thrown, and app does not start.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-os#80]
When attempting to install and run "Face App" from from [this video](https://youtu.be/8jkWwum8O8Q), an error is thrown, and app does not start.
```
(face-demo) Initialize Service: face

Cannot register component without name undefined
Uncaught exception:  TypeError: Cannot read property ‘prepare’ of undefined
```
Config
```
# do not touch this line
configVersion: 2

description: face detection
keywords: ''
name: face-demo
displayName: Face Demo

services:
  faceDemo:
    engine: detection
    type: face
```
